# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/dev/CSASA/vivaldo_starter/helloworld_working/helloworld_working.srcs/sources_1/bd/System/ip/System_axi_bram_ctrl_0_bram_0/System_axi_bram_ctrl_0_bram_0.xci
# IP: The module: 'System_axi_bram_ctrl_0_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/dev/CSASA/vivaldo_starter/helloworld_working/helloworld_working.srcs/sources_1/bd/System/ip/System_axi_bram_ctrl_0_bram_0/System_axi_bram_ctrl_0_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_axi_bram_ctrl_0_bram_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: h:/dev/CSASA/vivaldo_starter/helloworld_working/helloworld_working.srcs/sources_1/bd/System/ip/System_axi_bram_ctrl_0_bram_0/System_axi_bram_ctrl_0_bram_0.xci
# IP: The module: 'System_axi_bram_ctrl_0_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/dev/CSASA/vivaldo_starter/helloworld_working/helloworld_working.srcs/sources_1/bd/System/ip/System_axi_bram_ctrl_0_bram_0/System_axi_bram_ctrl_0_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_axi_bram_ctrl_0_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
