# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/System/System.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System || ORIG_REF_NAME==System} -quiet] -quiet

# IP: bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_processing_system7_0_0 || ORIG_REF_NAME==System_processing_system7_0_0} -quiet] -quiet

# IP: bd/System/ip/System_axi_bram_ctrl_0_0/System_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_bram_ctrl_0_0 || ORIG_REF_NAME==System_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/System/ip/System_axi_bram_ctrl_0_bram_0/System_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==System_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/System/ip/System_axi_smc_0/System_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_smc_0 || ORIG_REF_NAME==System_axi_smc_0} -quiet] -quiet

# IP: bd/System/ip/System_rst_ps7_0_50M_0/System_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_rst_ps7_0_50M_0 || ORIG_REF_NAME==System_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/System/System_ooc.xdc
